prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: monitoring
              operator: In
              values:
              - "true"
    tolerations:
      - key: "monitoring"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3 
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

    alertmanagerConfigSelector:
      matchLabels:
        release: prd-monitoring-stack 
    replicas: 1
    alertmanagerConfigMatcherStrategy:
      type: None

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: monitoring
              operator: In
              values:
              - "true"
    tolerations:
      - key: "monitoring"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

grafana:
  persistence:
    enabled: true
    storageClassName: "gp3"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: monitoring
                operator: In
                values:
                  - "true"
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"