loki:
  commonConfig:
    replication_factor: 1 

  storage:
    type: 'filesystem'
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage_config:
    filesystem:
      # directory: /tmp/loki/chunks
      directory: /var/loki/chunks      

  pattern_ingester:
    enabled: true

  limits_config:
    allow_structured_metadata: true
    retention_period: 168h
    volume_enabled: true

  ruler:
    enable_api: true

  auth_enabled: false

  minio:
    enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

  persistence:
    storageClass: gp3
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  tolerations:
    - operator: "Exists"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: monitoring
                operator: In
                values:
                  - "true"

  nodeSelector: {}

gateway:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: monitoring
                operator: In
                values:
                  - "true"
  tolerations:
    - operator: "Exists"

chunksCache:
  allocatedMemory: 1024
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: monitoring
                operator: In
                values:
                  - "true"
  tolerations:
    - operator: "Exists"

resultsCache:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: monitoring
                operator: In
                values:
                  - "true"
  tolerations:
    - operator: "Exists"

sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.0
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0