apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: loki   # Promtail no ns "loki"

  source:
    repoURL: https://github.com/wallafidevops/monitoring-eks-full.git
    targetRevision: main
    path: promtail
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
