apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/wallafidevops/monitoring-eks-full.git
    targetRevision: main
    path: kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    # ignore de réplicas nos Deployments principais do chart
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-operator
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-kube-state-metrics
      jsonPointers:
        - /spec/replicas
    # se existir HPA, ignore o status
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: kube-prometheus-stack-grafana
      jsonPointers:
        - /status/currentReplicas
        - /status/desiredReplicas
