apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    repoURL: https://github.com/wallafidevops/monitoring-eks-full.git
    targetRevision: main
    path: stack-loki
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: loki-gateway
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: loki
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: loki-results-cache
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: loki-chunks-cache
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: loki-gateway
      jsonPointers:
        - /status/currentReplicas
        - /status/desiredReplicas
