apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/wallafidevops/monitoring-eks-full.git
    targetRevision: main
    path: kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=Foreground ### remove recursos filhos antes do pai     
      - PruneLast=true ### remove o último recurso para não ter downtime    
      - ApplyOutOfSyncOnly=true ### aplica tudo que está fora de sincronia              
    ignoreDifferences:
      - group: apps
        kind: Deployment
        name: monitoring
        jsonPointers:
            - /spec/replicas
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        name: monitoring
        jsonPointers:
            - /status/currentReplicas
            - /status/desiredReplicas