apiVersion: v2
name: monitoring-stack
version: 0.1.0
type: application
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    # version: "77.6.2"
    version: "77.13.0"    